name: Kotlin Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Kodu çek
      uses: actions/checkout@v3

    - name: Java kur (Kotlin JVM için gerekli)
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '17'

    - name: Gradle kur ve derle
      uses: gradle/gradle-build-action@v2

    - name: Derleme çalıştır
      run: ./gradlew build